version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f Dockerfile .

     # deploy the image
     - run: |         
         docker login --username=$yannrogiers@gmail.com --password=$f80d5d26-dd6a-4a12-aee1-51a02870d076 registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$security-for-home/web
         docker push registry.heroku.com/$security-for-home/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $security-for-home
